### ISSUE TITLE
Checksum support

### ISSUE THREAD

**Issue by clement888** [mecachisenros/caldera-forms-civicrm#62]
Hello, would you be able to point me to documents on how to use the checksum support for the plugin ?  I have googled and didn't see any documents on how to use the checksum support particularly on how to form the right URL for this.  Thanks.

Clement

**Comment by danaskallman** [comment]
@clement888 there's reference to it in the [Features section of readme](https://github.com/mecachisenros/caldera-forms-civicrm#features), it would be something like this:

`example.com/support?cid={contact.contact_id}&{contact.checksum}`

The URL would be the WP page where the caldera form is added.

**Comment by clement888** [comment]
Hello Dana,

   Got it, that was useful.  i had thought the “support…” part of the example URL is to be added to the back of the form url.

    Is there a processor that can process the events tied to the contact ?  

    Thanks for you help.

Clement

**Comment by danaskallman** [comment]
There currently isn't an event processor, well really a participant processor, but it is planning. The main thing holding it up is lack of funding.

Glad that worked.

**Comment by mecachisenros** [comment]
Thank you for assisting with this @danaskallman

**Comment by andyburnsco** [comment]
Checksum does pre-fill but duplicates can be created by using Caldera Forms CiviCRM checksum. Wanting to note if someone else comes across this.

**Comment by mecachisenros** [comment]
@andyburnsco do you have any steps/details when duplicates are created? The dedupe in CFC is not bullet proof but I rarely get a duplicate, it would be useful to get more details to strengthen it.

**Comment by andyburnsco** [comment]
So as you know using a native civi profile the id is provided and it never creates a duplicate. 

My case was having organizational sub contact type using checksum. In the setup for contact processor it asks for a dedupe rule etc. For checksum, that should be ignored. The checksum is only successful in one direction in my testing, it pulls data from Civi but saving to civi it is using the dedupe rule set in the contact processor. If the data does not meet the dedupe rule set it creates a new record.

If I did not include the organization name it gave me a missing param error. I have not tested with individuals. 


What do you mean the dedupe in CFC? Something outside the rule set in contact processor?

**Comment by andyburnsco** [comment]
I have also now tested individuals and doesn't dedupe. My contact processor is first in order and has **'Auto populate contact data with CiviCRM data if user is logged in. (Only for the first contact processor)'** checked.

**Comment by mecachisenros** [comment]
@andyburnsco I see, thank you for the explanation.

> What do you mean the dedupe in CFC?

I was referring to how CFC [implements deduping](civi_contact_dedupe).

Just to summarise and to make sure we are on the same page, what you are saying is that we shouldn't dedupe at all via checksum, and stick with CiviCRM's Profile behaviour, correct?

The decision to dedupe again when the form is submitted was because we don't currently have a _Not Andrei Mondoc? Do you want to do this for a different contact..._ message, which would lead to contacts overriding existing contacts when forwarding emails.

As a side note, are you on the latest [stable version](https://github.com/mecachisenros/cf-civicrm/releases)? I ask because the wording for the **Auto populate** setting has changed and now it supports related contacts auto population adding a Relationship processor, and also, I believe there was an issue with Auto population in 1.0.2.

Another side note, CFC is now in the [WP plugin directory](https://wordpress.org/plugins/cf-civicrm/), I would recommend to deactivate and uninstall you current version and install it from the WP directory, unless you want to be in the _cutting edge_ (and less stable) `dev` branch.

**Comment by andyburnsco** [comment]
> I was referring to how CFC implements deduping.

That link does not take me anywhere.

> Just to summarise and to make sure we are on the same page, what you are saying is that we shouldn't dedupe at all via checksum, and stick with CiviCRM's Profile behaviour, correct?

Correct, checksum is supposed to take care of deduping. The CID is provided, therefore there should be no other deduping going on when checksum is present. The CID is known, there is nothing else needed...

> The decision to dedupe again when the form is submitted was because we don't currently have a Not Andrei Mondoc? Do you want to do this for a different contact... message, which would lead to contacts overriding existing contacts when forwarding emails.

I think the days of forwarding emails is getting less and less. The message would be good, but I always put a note in the email saying **'this is your personalized link' etc.**

> As a side note, are you on the latest stable version? I ask because the wording for the Auto populate setting has changed and now it supports related contacts auto population adding a Relationship processor, and also, I believe there was an issue with Auto population in 1.0.2.

On 1.0.2.

> Another side note, CFC is now in the WP plugin directory, I would recommend to deactivate and uninstall you current version and install it from the WP directory, unless you want to be in the cutting edge (and less stable) dev branch.

Sounds good, will do.

**Comment by andyburnsco** [comment]
To get a checksum in CFC to always dedupe you need to auto populate hidden fields that meet your selected dedupe rule e.g. if rule is first last and email include first, last and email.
