### ISSUE TITLE
Checking for existing contacts on registration form submit

### ISSUE THREAD

**Issue by ivanchimeno** [mecachisenros/caldera-forms-civicrm#63]
Hi @mecachisenros,

first of all thank you for developing the plugin, it's amazing and very powerful! 

I have a question regarding registering new contacts in CiviCRM via a registration form: I am currently using the contact processor to capture input from the user and finally creating a contact entry within CiviCRM. My problem is the fact that a duplicates are created when e.g the same name/email have been used. I tried the dedupe rules (Name/Email supervised and Name/Email unsupervised) but they don't seem to work. My solution would be to create a custom processor that attempts to retrieve a CiviCRM contact having the same first, last names and email and returning true/false wether they exist (and then return an error if a contact does exist). This leads to my question: is it possible to execute the processor before your contact processor is executed?

Best regards,
Ivan

**Comment by mecachisenros** [comment]
@ivanchimeno glad you find the plugin useful!

A few things:
1. What you describe seems to be a bug or a misconfiguration, so before you start creating a new Processor, can you let me know what WP/Civi and Caldera Forms (CF) and Caldera Forms CiviCRM (CFC) version you are using, and if possible attach an export of the form in question here?
2. Re custom processor - when you register a Processor you have three callbacks for different purposes/stages:
    + `pre_processor` - for any data processing that must be successful for the submission to be complete, `return`ing an error here will stop the form processing 
    + `processor` - runs after the pending entry is created, errors `return`ed here will show only after all processing is done
    + `post_processor` - runs before final entry is saved and emails are sent

That said, (in an ideal scenario) you shouldn't need to create another processor, the plugin *should* be _pluggable_ (hooks) enough to allow you to change and modify behavior. Unfortunately I haven't got there yet, so I suggest we try find the bug first.

**Comment by mecachisenros** [comment]
@ivanchimeno Got you, also the issue should be fixed via a75a6dec9ba0e96a1ff9743f667bb1df5002674c if you can test and report back would be great.

By `plugin should be pluggable (hooks)` I meant this plugin integration (CFC).

The Contact processor creation/update it's hooked to the `pre_processor` callback already, what I was trying  to say is that ideally you would have a *hook/s* which allow to plug your callbacks into the current Contact Processor, for example (it's just an example, as I said I need to look at this properly to see where and what hooks are apprpriate) you would have a filter and an action like:
```
...
// allow filtering of submitted values and dedupe params
apply_filters( 'cfc_civicrm_contact_pre_create_update_values', array( 'form_values' => $form_values, 'dedupe_params' => $dedupe_params ) );

...
// broadcast that a contact has been created/updated
do_action( 'cfc_civicrm_contact_created_updated', $created_contact );
```
So you wouldn't need to create a custom processor but just plug your callbacks to the filter/action.

Regarding the Processor's order execution, yes you are correct, they run in a loop **and** in the order they are added to the form, however, this integration **does alter the order** of the Contact Processors at form save time ([see here](https://github.com/mecachisenros/caldera-forms-civicrm/blob/master/includes/class-civicrm-caldera-forms-forms.php#L27)), meaning the all Contact Processors will be moved at the top and *processed* before any other processor. The reason to moved them at the was because all entities (Activity, Group, Tag, Relationship Processors) relay on the Contact processor, if that makes sense.

You can remove the reordering behavior calling `remove_filter( 'caldera_forms_presave_form', array( 'CiviCRM_Caldera_Forms_Forms', 'reorder_contact_processors' ), 20 )` in your plugin or functions file.

**Comment by ivanchimeno** [comment]
@mecachisenros Thank you for your reply. I have tested the dedupe rules against the latest commit on the master branch and can say that it works!

**Comment by mecachisenros** [comment]
@ivanchimeno Perfect! I'll close this issue then.
